pip install torch==2.0.1
pip install torchvision==0.15.2
pip install torchaudio==2.0.2
pip install decord
pip install h5py
pip install ffmpeg-python
pip install yacs
pip install toolz
pip install ipdb
pip install einops
pip install easydict
pip install transformers==4.31.0
pip install webdataset
pip install SentencePiece
